set_property PACKAGE_PIN N11 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P16 [get_ports cmos_href]
set_property PACKAGE_PIN P15 [get_ports cmos_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_pclk]
set_property PACKAGE_PIN R15 [get_ports cmos_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_pwdn]
set_property PACKAGE_PIN T12 [get_ports cmos_pwdn]
set_property PACKAGE_PIN R12 [get_ports cmos_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_rst_n]
set_property PACKAGE_PIN M16 [get_ports cmos_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_scl]
set_property PACKAGE_PIN N16 [get_ports cmos_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_sda]
set_property PACKAGE_PIN R16 [get_ports cmos_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_xclk]



set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[0]}]
set_property -dict {PACKAGE_PIN C8 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[1]}]
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[2]}]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[3]}]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[4]}]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[5]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[6]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[7]}]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[8]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[9]}]
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[10]}]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[11]}]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[12]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[13]}]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[14]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports {sdram_dq[15]}]

set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[0]}]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[1]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[2]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[4]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[5]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[6]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[7]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[8]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[9]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[10]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[11]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {sdram_addr[12]}]


set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports {sdram_ba[0]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {sdram_ba[1]}]

set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS33} [get_ports {sdram_dqm[0]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {sdram_dqm[1]}]

set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports sdram_clk]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports sdram_cke]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports sdram_cs_n]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports sdram_we_n]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports sdram_cas_n]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports sdram_ras_n]


set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports vga_out_hs]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports vga_out_vs]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {vga_out_r[0]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS33} [get_ports {vga_out_r[1]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports {vga_out_r[2]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {vga_out_r[3]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {vga_out_g[0]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports {vga_out_g[1]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports {vga_out_g[2]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {vga_out_g[3]}]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS33} [get_ports {vga_out_b[0]}]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports {vga_out_b[1]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {vga_out_b[2]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {vga_out_b[3]}]


set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {cmos_db[7]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {cmos_db[6]}]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports {cmos_db[5]}]
set_property -dict {PACKAGE_PIN P13 IOSTANDARD LVCMOS33} [get_ports {cmos_db[4]}]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {cmos_db[3]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {cmos_db[2]}]
set_property -dict {PACKAGE_PIN P10 IOSTANDARD LVCMOS33} [get_ports {cmos_db[1]}]
set_property -dict {PACKAGE_PIN P11 IOSTANDARD LVCMOS33} [get_ports {cmos_db[0]}]


set_property PACKAGE_PIN k13 [get_ports {key[0]}]
set_property PACKAGE_PIN L13 [get_ports {key[1]}]
set_property PACKAGE_PIN l14 [get_ports {key[2]}]
set_property PACKAGE_PIN M12 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN J3 [get_ports {led[0]}]
set_property PACKAGE_PIN H3 [get_ports {led[1]}]
set_property PACKAGE_PIN J1 [get_ports {led[2]}]
set_property PACKAGE_PIN K1 [get_ports {led[3]}]
set_property PACKAGE_PIN M6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]


# Allow non-dedicated routing for the top-level clock
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

# Allow non-dedicated routing for the internal clock buffer output
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -of_objects [get_pins m0/m1/clkout1_buf/O]]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_r[4]}]

# Grayscale Toggle Switch
set_property PACKAGE_PIN P8 [get_ports sw_grayscale]
set_property IOSTANDARD LVCMOS33 [get_ports sw_grayscale]
